# Generated by Django 4.0.5 on 2022-07-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_book_book_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=120, verbose_name='Book Name'),
        ),
    ]
